# Generated by Django 5.0.1 on 2024-01-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products')),
                ('coats', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField()),
            ],
        ),
    ]
